### ISSUE TITLE
Duplicate timeseries when using m3 query fanout

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2184] opened 2020-02-28 21:58 UTC
When cutting over writes to a new cluster, we noticed that prometheus was getting 2 copies of every timeseries for a short window after the cut. Our prometheus is set to remote read from m3-query which is configured to fanout. It appears as though m3query isn't merging the 2 copies of the data (from before and after the cutover) even though the labels align completely, and there's no datapoint overlap.

If we instead configure prometheus to remote-read from each m3-query, and disable fanout, prometheus is able to correctly merge the data from the multiple sources into one timeseries.

## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
m3-query
2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
multiple m3-queries, each configured to talk to 1 namespace, but fanning out to each other.
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
reads from prometheus
4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
We cut writes over from one cluster to another as part of a migration

**Comment by sboschman** [comment] 2020-03-06 08:35
Similar issue with duplicate timeseries, but within a single cluster, just two namespaces. One unaggregated namespace and one aggregated namespace. The unaggregated namespace has a 72 hour retention. Whenever data from both namespaces is needed to fullfill the query range two results are returned for the same timeserie.

@BertHartm  How did you disable fanout? Could you perhaps share the m3query yaml config?

**Comment by BertHartm** [comment] 2020-06-13 12:17
@sboschman this was a different use case as we weren't using aggregation, but in general we set each m3query instance to only have 1 namespace and let prom dedupe the data. May not work as well for aggregated manages.

**Comment by gibbscullen** [comment] 2020-07-10 17:43
Closing as this is the intended behavior.

**Comment by BertHartm** [comment] 2020-10-23 15:30
@gibbscullen I'd argue this shouldn't be intended as it basically breaks promql. Was hoping to reopen and looking at ways of fixing soon. Any idea on the intention?

**Comment by gibbscullen** [comment] 2021-01-06 15:49
Similar issue to 3034

**Comment by gibbscullen** [comment] 2021-01-28 16:43
Closing as this issue has been resolved.

**Closed by gibbscullen** 2021-01-28 16:43 UTC
