### ISSUE TITLE
api/v1/series returns wrong series with certain queries

### ISSUE THREAD

**Issue by arnaud-mey** [m3db/m3#1501] opened 2019-03-27 14:55 UTC
After setting up the cluster and ingesting data from prometheus we are facing a problem with the series API.
```curl 'http://localhost:7201/api/v1/series?match[]=up\{\}'```
is a never ending stream of json (we stopped at 8GB)
```curl 'http://localhost:7201/api/v1/series?match[]=up\{job="kube-state-metrics"\}'```
just returns a single data object (as expected). Grafana tries to utilize this API to get a list of labels (`label_values()`).
We are using m3dbnode v0.7.3 with m3operator v0.1.4.
Is this a bug or are we doing anything wrong? Our configuration is pretty much that fo the documentation. If you need any more infos from us, please let us know. Thanks in advance.

**Comment by richardartoul** [comment] 2019-03-28 02:29
@arnikola @benraskin92 Can one of you chime in here? Is this related to the new API we're building or is this a separate issue

**Comment by evanhuang996** [comment] 2019-03-28 07:26
I think it's related to https://github.com/m3db/m3/issues/1453

**Comment by evanhuang996** [comment] 2019-03-28 07:36
@arnaud-mey If you want a quick fix, just change the query path to Prometheus->m3query or m3coordinator->m3db

**Comment by arnaud-mey** [comment] 2019-03-28 15:22
Thanks for your reply. We put a Prometheus in front of the m3coordinator using the remote read api. That seems to work quite well.

**Comment by arnikola** [comment] 2019-03-28 15:56
Yeah, it's the same issue as #1453; although the root cause of the issue you're seeing is a bit different, but it should be fixed in #1481

**Comment by robskillington** [comment] 2019-03-30 00:19
Now that 0.8.0 is released, can we verify this behavior is no longer an issue and close this?

**Comment by evanhuang996** [comment] 2019-03-30 08:01
It's working well now.

**Comment by arnikola** [comment] 2019-03-30 17:13
Great to hear, thanks :+1:

**Closed by arnikola** 2019-03-30 17:13 UTC

**Comment by arnikola** [comment] 2019-04-03 14:41
@arnaud-mey we would recommend not putting a prom in front of coordinator; you're likely to get better performance connecting graphana directly to query now that 0.8.0 is landed

**Comment by arnaud-mey** [comment] 2019-04-04 07:58
yeah we tested 0.8.0 by now and we get the expected behavior now :)

thanks a lot!
