### ISSUE TITLE
Non-retryable Prometheus remote write errors should return 400

### ISSUE THREAD

**Issue by murphyzlaw** [m3db/m3#1709] opened 2019-06-06 14:54 UTC
Following is a software issue for Prometheus remote write and occurs on all O/S, hardware type, and M3 and Prometheus configurations.

Once samples get older than value of the bufferPastDuration in the namespace, each sample will be rejected outright with a 500 error. However the Prometheus remote write API considers 5xx errors retryable: https://github.com/prometheus/prometheus/blob/master/storage/remote/client.go#L111

M3 should return 400 for the too old data instead, as the condition will never self-fix.

The Prometheus issue https://github.com/prometheus/prometheus/issues/5636 makes the impact more severe, because failed (too old) samples will retry indefinitely, stopping metrics flow completely from the given Prometheus.

Issue observed for "timestamp too far in the past" but other non-retryable errors may also experience this.

**Comment by robskillington** [comment] 2019-06-06 19:05
Agreed, I've opened PR #1692 to address this with a docker integration test to ensure this is checked by CI moving forward too.

**Comment by richardartoul** [comment] 2019-06-13 13:58
@robskillington is it safe to close this or do we still have some pending work?

**Comment by robskillington** [comment] 2019-06-21 12:25
Closing this, confirmed working as intended now

**Closed by robskillington** 2019-06-21 12:25 UTC
