### ISSUE TITLE
dbnode may hang on to file descriptors for unowned shards

### ISSUE THREAD

**Issue by schallert** [m3db/m3#1125] opened 2018-10-23 15:45 UTC
On clusters with long retention, we've seen that the dbnode process may hang on to file descriptors for shards it no longer owns, while those shards are still in the retention period. This can lead to low disk space scenarios as the Linux kernel will count the size of files with open FDs against disk space, even if the file has been deleted and there's actually plenty of space on disk.

Restarting the process fixes the issue and the host immediately reclaims disk space.

Example (some data redacted):
```
$ sudo grep deleted /proc/$(pgrep m3dbnode)/maps | tail | awk '{print $6, $7}'
/var/lib/m3db/data/NAMESPACE/11/fileset-1539475200000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/0/fileset-1539475200000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/14/fileset-1539388800000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/11/fileset-1539388800000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/0/fileset-1539388800000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/11/fileset-1539302400000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/0/fileset-1539302400000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/14/fileset-1539216000000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/11/fileset-1539216000000000000-index.db (deleted)
/var/lib/m3db/data/NAMESPACE/0/fileset-1539216000000000000-index.db (deleted)

$ ls /var/lib/m3db/data/NAMESPACE/0
ls: cannot access /var/lib/m3db/data/NAMESPACE/0: No such file or directory
$ ls /var/lib/m3db/data/NAMESPACE/11
ls: cannot access /var/lib/m3db/data/NAMESPACE/11: No such file or directory

$ df -h DEV
Filesystem      Size  Used Avail Use% Mounted on
DEV             XXXG  595G  XXXG  XX% /

$ sudo du -hs /
338G    /

## Restart m3db process

$ df -h DEV
Filesystem      Size  Used Avail Use% Mounted on
DEV             XXXG  391G  XXXG  XX% /
```

**Comment by richardartoul** [comment] 2018-10-23 17:16
This issue is caused by the fact that when we remove shards from the topology, the SeekManager never gets informed that the node owns less shards now. As a result, the SeekManager never closes the file handles it has for the files in the shards that the node no longer owns. In order to fix this issue, we will need to propagate some kind of notification to the SeekManager when the placement changes such that the node owns less shards so that it can close its file handles.

For right now, operators that run into this issue have two workarounds:

1. Wait for the data to fall out of retention, at which point the SeekManager will close the file handles and the O.S can cleanup the files.
2 .Restart the nodes.

**Closed** 2020-09-18 16:54 UTC
Labels: C: Filesystem, C: Storage, P: Medium, T: Bug, T: Optimization, T: Perf, area:db
