### ISSUE TITLE
stuck in initializing state for long retention periods

### ISSUE THREAD

**Issue by arnaud-mey** [m3db/m3#1577] opened 2019-04-20 11:19 UTC
Hi there,
all shards are stuck in the initializing state. We suspect that this behavior is caused by a long retention time (~13 months) since it doesn't appear for short retention times.
We are using m3dbnode v0.8.0 with m3operator v0.1.4.
We are seeing the following log entries on all nodes:
```
11:07:36.413636[E] error when flushing data for time 2019-04-20 11:07:26.410666894 +0000 UTC m=+156095.694151320: persist manager cannot start persist, not idle

11:07:37.377660[D] not bootstrapped and durable because: no last snapshot start time [{lastBootstrapCompletionTime 2019-04-18 15:47:44.90400145 +0000 UTC m=+114.187485904} {lastSnapshotStartTime 0001-01-01 00:00:00 +0000 UTC}]
```
Our namespace config:
```
spec:
  numberOfShards: 256
  replicationFactor: 3
  namespaces:
  - name: default
    options:
      bootstrapEnabled: true
      flushEnabled: true
      writesToCommitLog: true
      cleanupEnabled: true
      repairEnabled: false
      snapshotEnabled: true
      retentionOptions:
        retentionPeriod: "9516h" 
        blockSize: "2h"
        bufferFuture: "10m"
        bufferPast: "10m"
        blockDataExpiry: true
        blockDataExpiryAfterNotAccessPeriod: "5m"
      indexOptions:
        enabled: true
        blockSize: "4h"

```

**Comment by richardartoul** [comment] 2019-04-20 16:56
@arnaud-mey I believe this is a dupe of #1563

We're aware of the issue. This is an unintended side-effect of changes we made to improve M3DB's durability during topology changes. Previously there was a brief period of time after a topology change where if a node crashed you could lose a replication factor. We've resolved that issue but as a result when a new cluster is created the shards won't become available until all of the files for the all of the blocks for all of the shards for the entire retention have been flushed.

We're aware this is an issue, but don't have a good solution right now except for using less shards or lower retention.

On the bright side, you only have to do this one time when you first create the cluster. Even if your node crash or restart you'll never have to do this again.

**Comment by arnaud-mey** [comment] 2019-04-22 08:24
I've stopped the cluster creation after approximately 72h. 
I tried to use less shards (16 with RF=3) according to your answer and all shards have been initialized after a few hours in that case. I'll try again with an intermediate value, though it could be that even 16 is a good value since we expect not much data in this database.

**Comment by richardartoul** [comment] 2019-04-23 16:48
Gonna close this as a duplicate of #1563 and continue the discussion there.

**Closed by richardartoul** 2019-04-23 16:48 UTC
